[project]
name = "overpass-ql-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.18.2",
    "pydantic>=2.11.9",
    "ruff>=0.13.3",
]
